SRC = HumanA.cpp HumanB.cpp Weapon.cpp main.cpp
NAME = Lets_Rock
CC = c++ -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRC)
	$(CC) $(SRC) -o $(NAME)

clean:
	rm -rf $(NAME)

fclean: clean

re: fclean all